create extension if not exists pgcrypto;
create type public.status_cliente as enum ('ativo','inativo','suspenso');
create type public.status_financeiro as enum ('pendente','pago','atrasado','cancelado');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, nome text, role text not null default 'admin' check(role='admin'), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.clientes(id uuid primary key default gen_random_uuid(), razao_social text not null, nome_fantasia text, cpf_cnpj text not null unique, telefone text, email text, cidade text, estado char(2), produto_contratado text, valor_mensalidade numeric(14,2) not null default 0 check(valor_mensalidade>=0), valor_implantacao numeric(14,2) not null default 0 check(valor_implantacao>=0), dia_vencimento smallint check(dia_vencimento between 1 and 31), data_inicio date, status public.status_cliente not null default 'ativo', observacoes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categorias_receitas(id uuid primary key default gen_random_uuid(), nome text not null unique, ativo boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categorias_despesas(id uuid primary key default gen_random_uuid(), nome text not null unique, ativo boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.receitas(id uuid primary key default gen_random_uuid(), cliente_id uuid references public.clientes(id) on delete set null, descricao text not null, categoria text, tipo text not null check(tipo in('mensalidade','implantacao','servico','venda','outro')), valor numeric(14,2) not null check(valor>=0), data_vencimento date not null, data_recebimento date, forma_pagamento text check(forma_pagamento in('PIX','Transferência','Boleto','Dinheiro','Cartão','Outro')), status public.status_financeiro not null default 'pendente', observacoes text, comprovante_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.despesas(id uuid primary key default gen_random_uuid(), descricao text not null, categoria text, fornecedor text, valor numeric(14,2) not null check(valor>=0), data_vencimento date not null, data_pagamento date, forma_pagamento text check(forma_pagamento in('PIX','Transferência','Boleto','Dinheiro','Cartão','Outro')), status public.status_financeiro not null default 'pendente', recorrente boolean not null default false, observacoes text, comprovante_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.retiradas(id uuid primary key default gen_random_uuid(), data date not null, valor numeric(14,2) not null check(valor>=0), tipo text not null check(tipo in('retirada_proprietario','pro_labore','distribuicao','outro')), descricao text not null, observacoes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.configuracoes_empresa(id uuid primary key default gen_random_uuid(), nome_empresa text, razao_social text, cnpj text, telefone text, email text, endereco text, cidade text, estado char(2), pix text, banco text, agencia text, conta text, logo_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.anexos(id uuid primary key default gen_random_uuid(), receita_id uuid references public.receitas(id) on delete cascade, despesa_id uuid references public.despesas(id) on delete cascade, nome_arquivo text not null, url text not null, mime_type text, tamanho bigint, created_at timestamptz not null default now(), check(num_nonnulls(receita_id,despesa_id)=1));

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','clientes','categorias_receitas','categorias_despesas','receitas','despesas','retiradas','configuracoes_empresa'] loop execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t); end loop; end $$;
create index receitas_cliente_idx on public.receitas(cliente_id);create index receitas_vencimento_status_idx on public.receitas(data_vencimento,status);create index receitas_recebimento_idx on public.receitas(data_recebimento);create index despesas_vencimento_status_idx on public.despesas(data_vencimento,status);create index despesas_pagamento_idx on public.despesas(data_pagamento);create index retiradas_data_idx on public.retiradas(data);create index clientes_status_idx on public.clientes(status);create index anexos_receita_idx on public.anexos(receita_id);create index anexos_despesa_idx on public.anexos(despesa_id);
insert into public.categorias_despesas(nome) values ('Hospedagem'),('Domínio'),('Supabase'),('Software'),('Internet'),('Equipamentos'),('Marketing'),('Contabilidade'),('Impostos'),('Serviços'),('Transporte'),('Outros') on conflict do nothing;
insert into public.categorias_receitas(nome) values ('Mensalidade'),('Implantação'),('Serviço'),('Venda'),('Outros') on conflict do nothing;

do $$ declare t text; begin foreach t in array array['profiles','clientes','categorias_receitas','categorias_despesas','receitas','despesas','retiradas','configuracoes_empresa','anexos'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy "authenticated_all" on public.%I for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null)',t); end loop; end $$;
grant usage on schema public to authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('comprovantes','comprovantes',false,10485760,array['application/pdf','image/jpeg','image/png']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "authenticated_read_receipts" on storage.objects for select to authenticated using(bucket_id='comprovantes' and (select auth.uid()) is not null);
create policy "authenticated_insert_receipts" on storage.objects for insert to authenticated with check(bucket_id='comprovantes' and (select auth.uid())::text=(storage.foldername(name))[1]);
create policy "authenticated_update_receipts" on storage.objects for update to authenticated using(bucket_id='comprovantes' and (select auth.uid())::text=(storage.foldername(name))[1]) with check(bucket_id='comprovantes' and (select auth.uid())::text=(storage.foldername(name))[1]);
create policy "authenticated_delete_receipts" on storage.objects for delete to authenticated using(bucket_id='comprovantes' and (select auth.uid())::text=(storage.foldername(name))[1]);
